// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using prriva_10;

#nullable disable

namespace prriva_10.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrivozsTovars", b =>
                {
                    b.Property<int>("PrivozsID")
                        .HasColumnType("int");

                    b.Property<int>("TovarID")
                        .HasColumnType("int");

                    b.HasKey("PrivozsID", "TovarID");

                    b.HasIndex("TovarID");

                    b.ToTable("PrivozsTovars");
                });

            modelBuilder.Entity("ProdajasTovars", b =>
                {
                    b.Property<int>("ProdajasID")
                        .HasColumnType("int");

                    b.Property<int>("TovarsID")
                        .HasColumnType("int");

                    b.HasKey("ProdajasID", "TovarsID");

                    b.HasIndex("TovarsID");

                    b.ToTable("ProdajasTovars");
                });

            modelBuilder.Entity("prriva_10.Izmers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Izmers");
                });

            modelBuilder.Entity("prriva_10.Kategors", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Kategors");
                });

            modelBuilder.Entity("prriva_10.Privozs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kolvo")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Privozs");
                });

            modelBuilder.Entity("prriva_10.Prodajas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kolvo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Prodajas");
                });

            modelBuilder.Entity("prriva_10.Tovars", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("IzmerID")
                        .HasColumnType("int");

                    b.Property<int>("KategorID")
                        .HasColumnType("int");

                    b.Property<int>("Kol_vo")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IzmerID");

                    b.HasIndex("KategorID");

                    b.ToTable("Tovar");
                });

            modelBuilder.Entity("PrivozsTovars", b =>
                {
                    b.HasOne("prriva_10.Privozs", null)
                        .WithMany()
                        .HasForeignKey("PrivozsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("prriva_10.Tovars", null)
                        .WithMany()
                        .HasForeignKey("TovarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProdajasTovars", b =>
                {
                    b.HasOne("prriva_10.Prodajas", null)
                        .WithMany()
                        .HasForeignKey("ProdajasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("prriva_10.Tovars", null)
                        .WithMany()
                        .HasForeignKey("TovarsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("prriva_10.Tovars", b =>
                {
                    b.HasOne("prriva_10.Izmers", "Izmer")
                        .WithMany("Tovars")
                        .HasForeignKey("IzmerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("prriva_10.Kategors", "Kategor")
                        .WithMany("Tovars")
                        .HasForeignKey("KategorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Izmer");

                    b.Navigation("Kategor");
                });

            modelBuilder.Entity("prriva_10.Izmers", b =>
                {
                    b.Navigation("Tovars");
                });

            modelBuilder.Entity("prriva_10.Kategors", b =>
                {
                    b.Navigation("Tovars");
                });
#pragma warning restore 612, 618
        }
    }
}
